spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}