spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres